# fly.toml app configuration file generated for public-library-backend on 2024-02-17T20:59:38-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'public-library-backend'
primary_region = 'dfw'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
